app:
  ruby-version: "2.4.0"
  git-url: "https://github.com/Hiroyuki-Nagata/fuzzy-giggle"
  branch: "master"
  app-name: "fuzzy-giggle"
  conf-name: "fuzzy-giggle.conf"
db:
  mysql-root-password: "R9NWaXGb%G!z"
